#define TECLA_TRUE 0xFF
#define TECLA_FALSE 0x00


#define AMUNT      72
#define DRETA      77
#define ESQUERRA   75
#define AVALL      80

#define DISPAR     82
#define BOMBA      83
#define INTRO      224
#define ESCAPE     1
#define P          25



void InstalarTeclado(void);

/* Instala la rutina para la deteccion de los SCAN-CODES */

void DesinstalarTeclado(void);
/* Desinstala la rutina para la detecci¢n de los SCAN-CODES */

