#ifndef ALL_LIB
 #define ALL_LIB

// TIPUS I CONSTANTS DEFINIDES

 #include <stdio.h>
 #include <stdlib.h>
 #include <math.h>
 #include <conio.h>
 #include <mem.h>
 #include <alloc.h>
 #include <dos.h>
 #include <ctype.h>





// UTILITATS.

 #include "const.h"
 #include "tipus.h"
 #include "vgaregs.h"
 #include "grafics.h"
 #include "modex.h"
 #include "font.h"
 #include "paleta.h"
 #include "vscreen.h"
 #include "effects.h"
 #include "pcx.h"
 #include "util.h"
 #include "mouse.h"
// #include "Part.h"
// #include "Objecte.h"

#include "Conjunt.h"

// RUTINES DEL JOC EN SI.

 #include "sprites.h"


#endif
