#ifndef TECLAT_H
 #define TECLAT_H

#include "all_lib.h"

//  ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
//  ³Definicions Tecles Utilitzades al Joc³
//  ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
/*
#define UP           
#define DOWN
#define RIGHT
#define LEFT
#define UP_RIGHT
#define UP_LEFT
#define DOWN_RIGHT
#define DOWN_LEFT
#define SHOT
#define BOMB
*/


/*
   ÉÍÍÍÍÍÍÍÍÍÍÍ»
   º           º
   º CAP€ALERA º
   º           º
   ÈÍÍÍÍÍÍÍÍÍÍÍ¼

*/


void InstalarTeclat();
void NetejarBuffer();
void DesinstalarTeclat();



#endif
